import type { ShopCategory, ShopProduct } from "./catalog-types";
import { products0 } from "./products/products-0";
import { products1 } from "./products/products-1";
import { products2 } from "./products/products-2";
import { products3 } from "./products/products-3";
import { products4 } from "./products/products-4";

export const SHOP_CATEGORIES: Record<string, ShopCategory> = {"face":{"name":"Обличчя","description":"Догляд за шкірою обличчя: очищення, зволоження, активні сироватки та SPF."},"face/facial-oil-serum":{"name":"Facial Oil & Serum","description":"Сироватки та олії для цільового щоденного догляду."},"face/scrub-cleansers":{"name":"Scrub & Cleansers","description":"Делікатне очищення та ексфоліація шкіри."},"face/day-night-cream":{"name":"Day & Night Cream","description":"Денні та нічні креми для підтримки бар’єра шкіри."},"face/eye-cream":{"name":"Eye Cream","description":"Догляд за делікатною зоною навколо очей."},"face/sun-face-cream":{"name":"Sun Face Cream","description":"Щоденний сонцезахист та підтримка шкіри."},"body":{"name":"Тіло","description":"Щоденний догляд за шкірою тіла."},"body/body-lotions":{"name":"Body Lotions","description":"Зволожувальні засоби для м’якої та доглянутої шкіри."},"body/hand-foot-creams":{"name":"Hand & Foot Creams","description":"Інтенсивний догляд за руками та стопами."},"body/body-oils":{"name":"Body Oils","description":"Олії та концентровані формули для тіла."},"body/self-tanning":{"name":"Self-Tanning","description":"Засоби для рівномірного природного відтінку шкіри."},"body/personal-care":{"name":"Personal Care","description":"Засоби щоденної персональної гігієни."},"hair":{"name":"Волосся","description":"Очищення, кондиціонування, відновлення та стайлінг волосся."},"hair/shampoo-bars":{"name":"Shampoo Bars","description":"Тверді шампуні для компактного та ефективного очищення."},"hair/shampoo":{"name":"Shampoo","description":"Шампуні для різних потреб волосся та шкіри голови."},"hair/conditioners":{"name":"Conditioners","description":"Кондиціонери для м’якості, блиску та легкого розчісування."},"hair/hair-treatments":{"name":"Hair Treatments","description":"Маски та інтенсивні засоби для відновлення волосся."},"hair/styling":{"name":"Styling","description":"Фінішний догляд і стайлінг."},"gifts":{"name":"Сертифікат","description":"Подарунковий сертифікат RESET."}};

export const SHOP_PRODUCTS: ShopProduct[] = [...products0, ...products1, ...products2, ...products3, ...products4];
export const getShopProduct = (slug: string) => SHOP_PRODUCTS.find((product) => product.slug === slug);
export const getShopCategory = (slug: string) => SHOP_CATEGORIES[slug];
export const getProductsByCategory = (slug: string) => SHOP_PRODUCTS.filter((product) => !slug || slug === "all" || product.categories.some((category) => category === slug || category.startsWith(`${slug}/`)));
export const formatShopPrice = (value: number) => new Intl.NumberFormat("uk-UA", { style: "currency", currency: "UAH", maximumFractionDigits: 2 }).format(value);
