export type SeoContentPriority = "P1" | "P2" | "P3";

export type SeoContentPlanLink = {
  label: string;
  href: string;
};

export type SeoContentPlanItem = {
  slug: string;
  title: string;
  category: "dermatology" | "acne" | "rosacea" | "pigmentation" | "cosmetology" | "skin-care" | "nutrition";
  priority: SeoContentPriority;
  intent: "informational" | "comparison" | "pre-procedure" | "diagnostic";
  primaryKeyword: string;
  seoTitle: string;
  metaDescription: string;
  angle: string;
  moneyPage: SeoContentPlanLink;
  supportingPages: SeoContentPlanLink[];
};

export const SEO_CONTENT_PLAN: SeoContentPlanItem[] = [
  {
    slug: "koli-zvertatysia-do-dermatoloha",
    title: "Коли варто звернутися до дерматолога: симптоми, які не слід ігнорувати",
    category: "dermatology",
    priority: "P1",
    intent: "diagnostic",
    primaryKeyword: "коли звертатися до дерматолога",
    seoTitle: "Коли звертатися до дерматолога: основні симптоми | RESET Clinic",
    metaDescription: "Коли потрібна консультація дерматолога: тривалі висипання, свербіж, новоутворення, зміни родимок та інші симптоми, які потребують професійної оцінки.",
    angle: "Широкий upper-funnel матеріал, який переводить читача на консультацію дерматолога без дублювання комерційного запиту «дерматолог Львів».",
    moneyPage: { label: "Консультація дерматолога у Львові", href: "/dermatology/dermatologist-lviv/" },
    supportingPages: [
      { label: "Дерматологія", href: "/dermatology/" },
      { label: "Дерматоскопія", href: "/dermatology/dermoscopy/" },
    ],
  },
  {
    slug: "dermatoskopiia-shcho-pokazuie",
    title: "Дерматоскопія: що показує обстеження і коли воно потрібне",
    category: "dermatology",
    priority: "P1",
    intent: "pre-procedure",
    primaryKeyword: "що показує дерматоскопія",
    seoTitle: "Дерматоскопія: що показує і коли потрібна | RESET Clinic",
    metaDescription: "Пояснюємо, що таке дерматоскопія, які зміни шкіри оцінюють під час обстеження та коли лікар може рекомендувати дерматоскопію.",
    angle: "Інформаційний intent перед записом на процедуру; не конкурує з посадковою «дерматоскопія у Львові».",
    moneyPage: { label: "Дерматоскопія у RESET Clinic", href: "/dermatology/dermoscopy/" },
    supportingPages: [
      { label: "Родимки та новоутворення", href: "/dermatology/moles-skin-lesions/" },
      { label: "Консультація дерматолога", href: "/dermatology/dermatologist-lviv/" },
    ],
  },
  {
    slug: "rodymka-zminylasia-shcho-robyty",
    title: "Родимка змінилася: які ознаки потребують огляду дерматолога",
    category: "dermatology",
    priority: "P1",
    intent: "diagnostic",
    primaryKeyword: "родимка змінилася що робити",
    seoTitle: "Родимка змінилася: коли потрібен огляд | RESET Clinic",
    metaDescription: "Зміна форми, кольору, розміру або відчуттів у ділянці родимки — привід для професійного огляду. Пояснюємо, коли звернутися до дерматолога.",
    angle: "YMYL-safe матеріал без самодіагностики; веде до дерматоскопії та огляду новоутворень.",
    moneyPage: { label: "Родимки та новоутворення шкіри", href: "/dermatology/moles-skin-lesions/" },
    supportingPages: [
      { label: "Дерматоскопія", href: "/dermatology/dermoscopy/" },
      { label: "Консультація дерматолога", href: "/dermatology/dermatologist-lviv/" },
    ],
  },
  {
    slug: "seboreinyi-dermatyt-chy-lupa",
    title: "Себорейний дерматит чи лупа: у чому різниця і коли звертатися до лікаря",
    category: "dermatology",
    priority: "P2",
    intent: "comparison",
    primaryKeyword: "себорейний дерматит чи лупа",
    seoTitle: "Себорейний дерматит чи лупа: як відрізнити | RESET Clinic",
    metaDescription: "Лупа та себорейний дерматит можуть мати схожі прояви. Розбираємо ключові відмінності та ситуації, коли потрібна консультація дерматолога.",
    angle: "Comparison intent із переходом на лікування себорейного дерматиту.",
    moneyPage: { label: "Лікування себорейного дерматиту", href: "/dermatology/dermatitis/seborrheic-dermatitis-treatment/" },
    supportingPages: [
      { label: "Дерматити", href: "/dermatology/dermatitis/" },
      { label: "Консультація дерматолога", href: "/dermatology/dermatologist-lviv/" },
    ],
  },
  {
    slug: "atopichnyi-dermatyt-dohliad",
    title: "Догляд за шкірою при атопічному дерматиті: базові принципи",
    category: "dermatology",
    priority: "P2",
    intent: "informational",
    primaryKeyword: "догляд при атопічному дерматиті",
    seoTitle: "Догляд при атопічному дерматиті: базові принципи | RESET Clinic",
    metaDescription: "Як будувати щоденний догляд при атопічному дерматиті: очищення, зволоження, тригери та коли потрібна консультація дерматолога.",
    angle: "Практичний informational intent, який підтримує лікувальну сторінку без заміни медичної консультації.",
    moneyPage: { label: "Лікування атопічного дерматиту", href: "/dermatology/dermatitis/atopic-dermatitis-treatment/" },
    supportingPages: [
      { label: "Дерматити", href: "/dermatology/dermatitis/" },
      { label: "Чутлива шкіра", href: "/skin-problems/sensitive-skin/" },
    ],
  },
  {
    slug: "trykhoskopiia-pry-vypadinni-volossia",
    title: "Трихоскопія при випадінні волосся: навіщо її роблять",
    category: "dermatology",
    priority: "P2",
    intent: "pre-procedure",
    primaryKeyword: "трихоскопія при випадінні волосся",
    seoTitle: "Трихоскопія при випадінні волосся: навіщо потрібна | RESET Clinic",
    metaDescription: "Що оцінює трихоскопія, як вона допомагає при випадінні волосся та чому діагностика має передувати самостійному прийому добавок або процедур.",
    angle: "Підсилює трихологічний кластер і переводить на діагностику, а не на «шампуні від випадіння».",
    moneyPage: { label: "Трихоскопія", href: "/dermatology/trichoscopy/" },
    supportingPages: [
      { label: "Трихолог у Львові", href: "/dermatology/trichologist-lviv/" },
      { label: "Лікування випадіння волосся", href: "/dermatology/hair-loss-treatment/" },
    ],
  },

  {
    slug: "akne-u-doroslykh-prychyny",
    title: "Акне у дорослих: чому висипання можуть з’явитися після 25 років",
    category: "acne",
    priority: "P1",
    intent: "informational",
    primaryKeyword: "акне у дорослих причини",
    seoTitle: "Акне у дорослих: основні причини висипань | RESET Clinic",
    metaDescription: "Чому акне може зберігатися або з’явитися у дорослому віці: роль шкірного бар’єра, гормональних факторів, догляду та інших тригерів.",
    angle: "Високий informational intent з чітким переходом на problem page та лікування акне.",
    moneyPage: { label: "Лікування акне", href: "/dermatology/acne-treatment/" },
    supportingPages: [
      { label: "Акне: причини та симптоми", href: "/skin-problems/acne/" },
      { label: "Комедони та чорні цятки", href: "/skin-problems/comedones-blackheads/" },
    ],
  },
  {
    slug: "zakryti-komedony-chomu-ziavliaiutsia",
    title: "Закриті комедони: чому з’являються і чого не варто робити самостійно",
    category: "acne",
    priority: "P1",
    intent: "informational",
    primaryKeyword: "закриті комедони причини",
    seoTitle: "Закриті комедони: причини та помилки догляду | RESET Clinic",
    metaDescription: "Що таке закриті комедони, чому вони виникають, які помилки догляду можуть погіршувати стан і коли потрібна консультація дерматолога.",
    angle: "Long-tail запит із високою частотою побутових помилок; веде на комедони та акне.",
    moneyPage: { label: "Комедони та чорні цятки", href: "/skin-problems/comedones-blackheads/" },
    supportingPages: [
      { label: "Акне", href: "/skin-problems/acne/" },
      { label: "Лікування акне", href: "/dermatology/acne-treatment/" },
    ],
  },
  {
    slug: "postakne-pliamy-chy-rubtsi",
    title: "Постакне: як відрізнити плями від рубців і чому це важливо для тактики",
    category: "acne",
    priority: "P1",
    intent: "comparison",
    primaryKeyword: "плями чи рубці постакне",
    seoTitle: "Постакне: плями чи рубці — у чому різниця | RESET Clinic",
    metaDescription: "Постзапальні плями та рубці після акне — різні стани. Пояснюємо, чому їх важливо розрізняти перед вибором професійної корекції.",
    angle: "Comparison intent, що направляє до post-acne problem page і RF/процедур лише після оцінки.",
    moneyPage: { label: "Постакне", href: "/skin-problems/post-acne/" },
    supportingPages: [
      { label: "Мікроголковий RF", href: "/cosmetology/hardware/microneedle-rf/" },
      { label: "Лікування акне", href: "/dermatology/acne-treatment/" },
    ],
  },
  {
    slug: "chystka-oblychchia-pry-akne",
    title: "Чи можна робити чистку обличчя при акне",
    category: "acne",
    priority: "P2",
    intent: "pre-procedure",
    primaryKeyword: "чистка обличчя при акне",
    seoTitle: "Чистка обличчя при акне: коли можна, а коли ні | RESET Clinic",
    metaDescription: "Чи підходить чистка обличчя при акне, від чого залежить рішення та чому активне запалення потребує оцінки спеціаліста перед процедурою.",
    angle: "Процедурний informational intent без просування чистки як універсального лікування акне.",
    moneyPage: { label: "Лікування акне", href: "/dermatology/acne-treatment/" },
    supportingPages: [
      { label: "Акне", href: "/skin-problems/acne/" },
      { label: "Догляд за шкірою", href: "/skin-care/" },
    ],
  },
  {
    slug: "spirove-kharchuvannia-ta-akne",
    title: "Харчування та акне: що відомо про зв’язок раціону з висипаннями",
    category: "acne",
    priority: "P2",
    intent: "informational",
    primaryKeyword: "харчування і акне",
    seoTitle: "Харчування та акне: чи впливає раціон на висипання | RESET Clinic",
    metaDescription: "Розбираємо, що відомо про зв’язок харчування з акне, чому не варто будувати лікування лише на дієті та коли потрібна комплексна оцінка.",
    angle: "Перехресний кластер acne + nutrition без псевдомедичних обіцянок.",
    moneyPage: { label: "Лікування акне", href: "/dermatology/acne-treatment/" },
    supportingPages: [
      { label: "Нутриціологія", href: "/nutrition/" },
      { label: "Консультація нутриціолога", href: "/nutrition/nutritionist-lviv/" },
    ],
  },
  {
    slug: "spf-pry-akne-ta-postakne",
    title: "SPF при акне та постакне: навіщо потрібен фотозахист",
    category: "acne",
    priority: "P3",
    intent: "informational",
    primaryKeyword: "spf при акне",
    seoTitle: "SPF при акне та постакне: навіщо потрібен | RESET Clinic",
    metaDescription: "Навіщо використовувати фотозахист при акне та постакне, як сонце впливає на постзапальні плями та як обирати SPF без агресивних експериментів.",
    angle: "Support content для акне, постакне та пігментації.",
    moneyPage: { label: "Постакне", href: "/skin-problems/post-acne/" },
    supportingPages: [
      { label: "Акне", href: "/skin-problems/acne/" },
      { label: "Пігментація", href: "/skin-problems/pigmentation/" },
    ],
  },

  {
    slug: "rozatsea-chy-kuperoz",
    title: "Розацеа чи купероз: чим відрізняються почервоніння та судинні прояви",
    category: "rosacea",
    priority: "P1",
    intent: "comparison",
    primaryKeyword: "розацеа чи купероз",
    seoTitle: "Розацеа чи купероз: у чому різниця | RESET Clinic",
    metaDescription: "Почервоніння обличчя може мати різні причини. Пояснюємо різницю між розацеа, стійким почервонінням і судинними проявами без самодіагностики.",
    angle: "Сильний comparison intent, що розводить problem pages і процедуру IPL.",
    moneyPage: { label: "Лікування розацеа", href: "/dermatology/rosacea-treatment/" },
    supportingPages: [
      { label: "Розацеа", href: "/skin-problems/rosacea/" },
      { label: "Почервоніння шкіри", href: "/skin-problems/redness/" },
    ],
  },
  {
    slug: "tryhery-rozatsea",
    title: "Тригери розацеа: що може провокувати почервоніння та загострення",
    category: "rosacea",
    priority: "P1",
    intent: "informational",
    primaryKeyword: "тригери розацеа",
    seoTitle: "Тригери розацеа: що провокує загострення | RESET Clinic",
    metaDescription: "Температура, сонце, стрес, алкоголь, гостра їжа та інші фактори можуть бути індивідуальними тригерами розацеа. Пояснюємо, як вести спостереження.",
    angle: "Upper-funnel article з персоналізованим підходом, не перетворює список тригерів на універсальну дієту.",
    moneyPage: { label: "Лікування розацеа", href: "/dermatology/rosacea-treatment/" },
    supportingPages: [
      { label: "Розацеа", href: "/skin-problems/rosacea/" },
      { label: "Догляд за шкірою", href: "/skin-care/" },
    ],
  },
  {
    slug: "dohliad-za-shkiroiu-pry-rozatsea",
    title: "Догляд за шкірою при розацеа: як не посилювати реактивність",
    category: "rosacea",
    priority: "P1",
    intent: "informational",
    primaryKeyword: "догляд за шкірою при розацеа",
    seoTitle: "Догляд при розацеа: базові принципи | RESET Clinic",
    metaDescription: "М’яке очищення, відновлення бар’єра, фотозахист і обережність з активами — базові принципи догляду за реактивною шкірою при розацеа.",
    angle: "Практичний support content із перелінковкою на sensitive skin та rosacea treatment.",
    moneyPage: { label: "Лікування розацеа", href: "/dermatology/rosacea-treatment/" },
    supportingPages: [
      { label: "Чутлива шкіра", href: "/skin-problems/sensitive-skin/" },
      { label: "Почервоніння", href: "/skin-problems/redness/" },
    ],
  },
  {
    slug: "ipl-pry-rozatsea",
    title: "IPL при розацеа та почервонінні: які задачі може вирішувати фототерапія",
    category: "rosacea",
    priority: "P2",
    intent: "pre-procedure",
    primaryKeyword: "ipl при розацеа",
    seoTitle: "IPL при розацеа: коли розглядають фототерапію | RESET Clinic",
    metaDescription: "Коли IPL може розглядатися при судинних проявах і почервонінні, чого очікувати від процедури та чому вона не замінює лікування розацеа.",
    angle: "Зводить informational query до процедури IPL, але чітко відділяє лікування хвороби від корекції окремих проявів.",
    moneyPage: { label: "IPL-терапія", href: "/cosmetology/hardware/ipl/" },
    supportingPages: [
      { label: "Лікування розацеа", href: "/dermatology/rosacea-treatment/" },
      { label: "Почервоніння", href: "/skin-problems/redness/" },
    ],
  },
  {
    slug: "rozatsea-vlitku",
    title: "Розацеа влітку: як сонце і спека можуть впливати на шкіру",
    category: "rosacea",
    priority: "P2",
    intent: "informational",
    primaryKeyword: "розацеа влітку",
    seoTitle: "Розацеа влітку: сонце, спека і догляд | RESET Clinic",
    metaDescription: "Як сонце, спека та різкі перепади температур можуть впливати на розацеа і що варто врахувати в літньому догляді та фотозахисті.",
    angle: "Seasonal evergreen content із хорошою внутрішньою перелінковкою на догляд та лікування.",
    moneyPage: { label: "Лікування розацеа", href: "/dermatology/rosacea-treatment/" },
    supportingPages: [
      { label: "Розацеа", href: "/skin-problems/rosacea/" },
      { label: "Догляд за шкірою", href: "/skin-care/" },
    ],
  },
  {
    slug: "chutlyva-shkira-chy-rozatsea",
    title: "Чутлива шкіра чи розацеа: чому постійне почервоніння потребує оцінки",
    category: "rosacea",
    priority: "P3",
    intent: "comparison",
    primaryKeyword: "чутлива шкіра чи розацеа",
    seoTitle: "Чутлива шкіра чи розацеа: як відрізняються стани | RESET Clinic",
    metaDescription: "Реактивність, печіння та почервоніння можуть мати різні причини. Пояснюємо, чому чутлива шкіра та розацеа — не одне й те саме.",
    angle: "Comparison between problem pages, useful for topical authority.",
    moneyPage: { label: "Розацеа", href: "/skin-problems/rosacea/" },
    supportingPages: [
      { label: "Чутлива шкіра", href: "/skin-problems/sensitive-skin/" },
      { label: "Лікування розацеа", href: "/dermatology/rosacea-treatment/" },
    ],
  },

  {
    slug: "melazma-chy-pihmentni-pliamy",
    title: "Мелазма чи пігментні плями: чому важливо визначити тип пігментації",
    category: "pigmentation",
    priority: "P1",
    intent: "comparison",
    primaryKeyword: "мелазма чи пігментні плями",
    seoTitle: "Мелазма чи пігментні плями: у чому різниця | RESET Clinic",
    metaDescription: "Не всі пігментні плями однакові. Пояснюємо, чим мелазма відрізняється від інших типів гіперпігментації та чому тактика залежить від діагностики.",
    angle: "Comparison intent з переходом на pigmentation treatment; не обіцяє універсальне видалення плям.",
    moneyPage: { label: "Лікування пігментації", href: "/dermatology/pigmentation-treatment/" },
    supportingPages: [
      { label: "Пігментація", href: "/skin-problems/pigmentation/" },
      { label: "Діагностика шкіри", href: "/cosmetology/hardware/skin-diagnostics/" },
    ],
  },
  {
    slug: "pihmentni-pliamy-pislia-akne",
    title: "Пігментні плями після акне: чому вони залишаються і як відрізняються від рубців",
    category: "pigmentation",
    priority: "P1",
    intent: "informational",
    primaryKeyword: "пігментні плями після акне",
    seoTitle: "Пігментні плями після акне: причини та відмінності | RESET Clinic",
    metaDescription: "Після акне можуть залишатися постзапальні плями або рубці. Пояснюємо, чому це різні задачі і чому підхід до корекції відрізняється.",
    angle: "Bridge between pigmentation and post-acne clusters.",
    moneyPage: { label: "Постакне", href: "/skin-problems/post-acne/" },
    supportingPages: [
      { label: "Пігментація", href: "/skin-problems/pigmentation/" },
      { label: "Лікування пігментації", href: "/dermatology/pigmentation-treatment/" },
    ],
  },
  {
    slug: "spf-pry-pihmentatsii",
    title: "SPF при пігментації: чому фотозахист є частиною стратегії",
    category: "pigmentation",
    priority: "P1",
    intent: "informational",
    primaryKeyword: "spf при пігментації",
    seoTitle: "SPF при пігментації: навіщо потрібен фотозахист | RESET Clinic",
    metaDescription: "Чому ультрафіолет може підтримувати пігментацію, як фотозахист вписується у комплексний план та чому одного SPF іноді недостатньо.",
    angle: "Evergreen support article для pigmentation treatment та skin care.",
    moneyPage: { label: "Лікування пігментації", href: "/dermatology/pigmentation-treatment/" },
    supportingPages: [
      { label: "Пігментація", href: "/skin-problems/pigmentation/" },
      { label: "Догляд за шкірою", href: "/skin-care/" },
    ],
  },
  {
    slug: "ipl-vid-pihmentatsii",
    title: "IPL від пігментації: для яких змін шкіри може розглядатися фототерапія",
    category: "pigmentation",
    priority: "P2",
    intent: "pre-procedure",
    primaryKeyword: "ipl від пігментації",
    seoTitle: "IPL від пігментації: коли розглядають процедуру | RESET Clinic",
    metaDescription: "IPL може бути доречним для окремих типів пігментних змін. Пояснюємо показання, обмеження та чому перед процедурою важлива оцінка шкіри.",
    angle: "Pre-procedure intent, який переводить на IPL і pigmentation treatment без канібалізації service page.",
    moneyPage: { label: "IPL-терапія", href: "/cosmetology/hardware/ipl/" },
    supportingPages: [
      { label: "Лікування пігментації", href: "/dermatology/pigmentation-treatment/" },
      { label: "Діагностика шкіри", href: "/cosmetology/hardware/skin-diagnostics/" },
    ],
  },
  {
    slug: "pihmentatsiia-vlitku",
    title: "Пігментація влітку: що варто знати про сонце, активи та процедури",
    category: "pigmentation",
    priority: "P2",
    intent: "informational",
    primaryKeyword: "пігментація влітку",
    seoTitle: "Пігментація влітку: сонце, SPF та процедури | RESET Clinic",
    metaDescription: "Як літній сезон впливає на пігментацію, які принципи фотозахисту важливі та чому агресивні процедури й активи потребують обережного планування.",
    angle: "Seasonal evergreen article that can rank every spring-summer.",
    moneyPage: { label: "Лікування пігментації", href: "/dermatology/pigmentation-treatment/" },
    supportingPages: [
      { label: "Пігментація", href: "/skin-problems/pigmentation/" },
      { label: "IPL-терапія", href: "/cosmetology/hardware/ipl/" },
    ],
  },
  {
    slug: "nerivnyi-ton-shkiry-prychyny",
    title: "Нерівний тон шкіри: можливі причини і коли потрібна діагностика",
    category: "pigmentation",
    priority: "P3",
    intent: "diagnostic",
    primaryKeyword: "нерівний тон шкіри причини",
    seoTitle: "Нерівний тон шкіри: причини та діагностика | RESET Clinic",
    metaDescription: "Нерівний тон може бути пов’язаний із пігментацією, почервонінням, постакне та іншими станами. Пояснюємо, чому важливо визначити причину.",
    angle: "Problem-discovery content, which distributes to pigmentation/redness/diagnostics.",
    moneyPage: { label: "Нерівний тон шкіри", href: "/skin-problems/uneven-skin-tone/" },
    supportingPages: [
      { label: "Пігментація", href: "/skin-problems/pigmentation/" },
      { label: "Діагностика шкіри", href: "/cosmetology/hardware/skin-diagnostics/" },
    ],
  },

  {
    slug: "botoks-koly-pochnut-diiaty",
    title: "Коли починає діяти ботулотоксин і коли оцінюють результат",
    category: "cosmetology",
    priority: "P1",
    intent: "pre-procedure",
    primaryKeyword: "коли починає діяти ботокс",
    seoTitle: "Коли починає діяти ботулотоксин: строки результату | RESET Clinic",
    metaDescription: "Пояснюємо, коли зазвичай починають проявлятися ефекти ботулінотерапії, коли оцінюють результат і чому строки можуть відрізнятися.",
    angle: "High-intent informational query, який веде на botulinum therapy page.",
    moneyPage: { label: "Ботулінотерапія", href: "/cosmetology/injection/botulinum-therapy/" },
    supportingPages: [
      { label: "Ін’єкційна косметологія", href: "/cosmetology/injection/" },
      { label: "Ціни", href: "/price/" },
    ],
  },
  {
    slug: "botoks-chy-filer",
    title: "Ботулотоксин чи філер: різні задачі, різні механізми",
    category: "cosmetology",
    priority: "P1",
    intent: "comparison",
    primaryKeyword: "ботокс чи філер",
    seoTitle: "Ботулотоксин чи філер: у чому різниця | RESET Clinic",
    metaDescription: "Ботулінотерапія та філери вирішують різні естетичні задачі. Пояснюємо принципову різницю та чому метод обирають після оцінки анатомії й запиту.",
    angle: "Comparison intent that distributes authority to botulinum and contouring pages.",
    moneyPage: { label: "Ботулінотерапія", href: "/cosmetology/injection/botulinum-therapy/" },
    supportingPages: [
      { label: "Контурна пластика обличчя", href: "/cosmetology/injection/face-contouring/" },
      { label: "Ін’єкційна косметологія", href: "/cosmetology/injection/" },
    ],
  },
  {
    slug: "biorevitalizatsiia-chy-mezoterapiia",
    title: "Біоревіталізація чи мезотерапія: як відрізняються процедури",
    category: "cosmetology",
    priority: "P1",
    intent: "comparison",
    primaryKeyword: "біоревіталізація чи мезотерапія",
    seoTitle: "Біоревіталізація чи мезотерапія: різниця процедур | RESET Clinic",
    metaDescription: "Порівнюємо біоревіталізацію та мезотерапію за задачами, підходом і показаннями без універсальної відповіді «що краще».",
    angle: "Comparison content, що допомагає не створювати дві конкуруючі service pages під один intent.",
    moneyPage: { label: "Біоревіталізація", href: "/cosmetology/injection/biorevitalization/" },
    supportingPages: [
      { label: "Мезотерапія", href: "/cosmetology/injection/mesotherapy/" },
      { label: "Ін’єкційна косметологія", href: "/cosmetology/injection/" },
    ],
  },
  {
    slug: "mikroholkovyi-rf-vidnovlennia",
    title: "Мікроголковий RF: як проходить відновлення після процедури",
    category: "cosmetology",
    priority: "P2",
    intent: "pre-procedure",
    primaryKeyword: "мікроголковий rf відновлення",
    seoTitle: "Мікроголковий RF: відновлення після процедури | RESET Clinic",
    metaDescription: "Що може відбуватися зі шкірою після мікроголкового RF, які реакції очікувані та яких рекомендацій дотримуються у відновлювальний період.",
    angle: "Pre-procedure / aftercare intent for high-value service page.",
    moneyPage: { label: "Мікроголковий RF", href: "/cosmetology/hardware/microneedle-rf/" },
    supportingPages: [
      { label: "Нерівна текстура шкіри", href: "/skin-problems/uneven-skin-texture/" },
      { label: "Рубці", href: "/skin-problems/scars/" },
    ],
  },
  {
    slug: "ipl-chy-rf",
    title: "IPL чи RF: чому ці апаратні процедури не є взаємозамінними",
    category: "cosmetology",
    priority: "P2",
    intent: "comparison",
    primaryKeyword: "ipl чи rf",
    seoTitle: "IPL чи RF: у чому різниця процедур | RESET Clinic",
    metaDescription: "IPL працює зі світлом, RF — з радіочастотною енергією. Пояснюємо, чому процедури мають різні задачі та як обирають метод.",
    angle: "Comparison intent between two high-value hardware pages.",
    moneyPage: { label: "IPL-терапія", href: "/cosmetology/hardware/ipl/" },
    supportingPages: [
      { label: "Мікроголковий RF", href: "/cosmetology/hardware/microneedle-rf/" },
      { label: "Апаратна косметологія", href: "/cosmetology/hardware/" },
    ],
  },
  {
    slug: "zbilshennia-hubiv-pershyi-raz",
    title: "Збільшення губ уперше: що обговорити з лікарем до процедури",
    category: "cosmetology",
    priority: "P3",
    intent: "pre-procedure",
    primaryKeyword: "збільшення губ перший раз",
    seoTitle: "Збільшення губ уперше: підготовка до процедури | RESET Clinic",
    metaDescription: "Що важливо обговорити перед першою контурною пластикою губ: очікування, анатомію, препарат, протипоказання та план відновлення.",
    angle: "High-conversion pre-procedure content without promises about a specific aesthetic result.",
    moneyPage: { label: "Контурна пластика губ", href: "/cosmetology/injection/lip-contouring/" },
    supportingPages: [
      { label: "Ін’єкційна косметологія", href: "/cosmetology/injection/" },
      { label: "Ціни", href: "/price/" },
    ],
  },

  {
    slug: "yak-vyznachyty-typ-shkiry",
    title: "Як визначити тип і стан шкіри та чому це не одне й те саме",
    category: "skin-care",
    priority: "P1",
    intent: "informational",
    primaryKeyword: "як визначити тип шкіри",
    seoTitle: "Як визначити тип і стан шкіри | RESET Clinic",
    metaDescription: "Жирність, сухість, чутливість і зневоднення описують різні характеристики шкіри. Пояснюємо, як не плутати тип зі станом.",
    angle: "Core skin-care pillar article that sends users to diagnostics and specific problem pages.",
    moneyPage: { label: "Догляд за шкірою", href: "/skin-care/" },
    supportingPages: [
      { label: "Діагностика шкіри", href: "/cosmetology/hardware/skin-diagnostics/" },
      { label: "Суха шкіра", href: "/skin-problems/dry-skin/" },
    ],
  },
  {
    slug: "znehidratovana-chy-sukha-shkira",
    title: "Зневоднена чи суха шкіра: у чому різниця",
    category: "skin-care",
    priority: "P1",
    intent: "comparison",
    primaryKeyword: "зневоднена чи суха шкіра",
    seoTitle: "Зневоднена чи суха шкіра: різниця і догляд | RESET Clinic",
    metaDescription: "Сухість і зневоднення — не тотожні стани. Розбираємо відмінності, типові помилки догляду та коли потрібна професійна оцінка.",
    angle: "High-volume comparison-style educational topic supporting dry skin page.",
    moneyPage: { label: "Суха шкіра", href: "/skin-problems/dry-skin/" },
    supportingPages: [
      { label: "Догляд за шкірою", href: "/skin-care/" },
      { label: "Діагностика шкіри", href: "/cosmetology/hardware/skin-diagnostics/" },
    ],
  },
  {
    slug: "poshkodzhenyi-barier-shkiry",
    title: "Пошкоджений шкірний бар’єр: ознаки та помилки в догляді",
    category: "skin-care",
    priority: "P1",
    intent: "informational",
    primaryKeyword: "пошкоджений бар'єр шкіри",
    seoTitle: "Пошкоджений шкірний бар’єр: ознаки та догляд | RESET Clinic",
    metaDescription: "Стягнутість, печіння, реактивність і сухість можуть бути пов’язані з порушенням бар’єрної функції. Пояснюємо базові принципи відновлення.",
    angle: "Broad topical authority piece with links to sensitive and dry skin pages.",
    moneyPage: { label: "Чутлива шкіра", href: "/skin-problems/sensitive-skin/" },
    supportingPages: [
      { label: "Суха шкіра", href: "/skin-problems/dry-skin/" },
      { label: "Догляд за шкірою", href: "/skin-care/" },
    ],
  },
  {
    slug: "rozshyreni-pory-shcho-vplyvaie",
    title: "Розширені пори: що впливає на їх видимість",
    category: "skin-care",
    priority: "P2",
    intent: "informational",
    primaryKeyword: "розширені пори причини",
    seoTitle: "Розширені пори: причини та що впливає на видимість | RESET Clinic",
    metaDescription: "Себум, еластичність шкіри, комедони та текстура можуть впливати на видимість пор. Пояснюємо, чому «закрити пори» назавжди неможливо.",
    angle: "Myth-busting informational content leading to enlarged pores and texture pages.",
    moneyPage: { label: "Розширені пори", href: "/skin-problems/enlarged-pores/" },
    supportingPages: [
      { label: "Нерівна текстура", href: "/skin-problems/uneven-skin-texture/" },
      { label: "Комедони", href: "/skin-problems/comedones-blackheads/" },
    ],
  },
  {
    slug: "retinol-dlia-pochatkivtsiv",
    title: "Ретиноїди в домашньому догляді: що важливо знати перед стартом",
    category: "skin-care",
    priority: "P2",
    intent: "informational",
    primaryKeyword: "ретинол як почати",
    seoTitle: "Ретиноїди в догляді: як безпечно почати | RESET Clinic",
    metaDescription: "Що варто врахувати перед введенням ретиноїдів у догляд, чому важлива поступовість і в яких ситуаціях краще порадитися зі спеціалістом.",
    angle: "Evergreen ingredient content with safe medical framing.",
    moneyPage: { label: "Догляд за шкірою", href: "/skin-care/" },
    supportingPages: [
      { label: "Чутлива шкіра", href: "/skin-problems/sensitive-skin/" },
      { label: "Акне", href: "/skin-problems/acne/" },
    ],
  },
  {
    slug: "niatsynamid-kysloty-retinol-razom",
    title: "Ніацинамід, кислоти й ретиноїди: як не перевантажити догляд активами",
    category: "skin-care",
    priority: "P3",
    intent: "informational",
    primaryKeyword: "як поєднувати активи в догляді",
    seoTitle: "Як поєднувати активи в догляді без перевантаження | RESET Clinic",
    metaDescription: "Більше активів не означає кращий результат. Пояснюємо, як уникати надмірного нашарування кислот, ретиноїдів та інших активних компонентів.",
    angle: "Useful support content for barrier/sensitive skin and professional diagnostics.",
    moneyPage: { label: "Догляд за шкірою", href: "/skin-care/" },
    supportingPages: [
      { label: "Чутлива шкіра", href: "/skin-problems/sensitive-skin/" },
      { label: "Діагностика шкіри", href: "/cosmetology/hardware/skin-diagnostics/" },
    ],
  },

  {
    slug: "oznaky-defitsytu-zaliza",
    title: "Дефіцит заліза: які симптоми можуть бути приводом для обстеження",
    category: "nutrition",
    priority: "P1",
    intent: "diagnostic",
    primaryKeyword: "ознаки дефіциту заліза",
    seoTitle: "Дефіцит заліза: можливі симптоми та діагностика | RESET Clinic",
    metaDescription: "Втома, зміни волосся та інші неспецифічні симптоми можуть мати багато причин. Пояснюємо, чому дефіцит заліза підтверджують лабораторно.",
    angle: "YMYL-safe diagnostic content; no self-prescribing iron supplements.",
    moneyPage: { label: "Діагностика дефіцитів", href: "/nutrition/deficiency-diagnostics/" },
    supportingPages: [
      { label: "Вітамінно-мінеральні дефіцити", href: "/nutrition/vitamin-mineral-deficiencies/" },
      { label: "Консультація нутриціолога", href: "/nutrition/nutritionist-lviv/" },
    ],
  },
  {
    slug: "vitamin-d-koly-pereviriaty",
    title: "Вітамін D: коли доцільно перевіряти рівень і чому не варто приймати навмання",
    category: "nutrition",
    priority: "P1",
    intent: "diagnostic",
    primaryKeyword: "коли перевіряти вітамін d",
    seoTitle: "Вітамін D: коли перевіряти рівень | RESET Clinic",
    metaDescription: "Кому лікар може рекомендувати аналіз на вітамін D, чому симптоми неспецифічні та чому дозування добавок не підбирають без контексту.",
    angle: "Strong YMYL topic with safe lab-first framing.",
    moneyPage: { label: "Діагностика дефіцитів", href: "/nutrition/deficiency-diagnostics/" },
    supportingPages: [
      { label: "Вітамінно-мінеральні дефіцити", href: "/nutrition/vitamin-mineral-deficiencies/" },
      { label: "Нутриціологія", href: "/nutrition/" },
    ],
  },
  {
    slug: "vypadinnia-volossia-ta-defitsyty",
    title: "Випадіння волосся і дефіцити: чому аналізи підбирають за показаннями",
    category: "nutrition",
    priority: "P1",
    intent: "informational",
    primaryKeyword: "дефіцити при випадінні волосся",
    seoTitle: "Випадіння волосся і дефіцити: які аналізи потрібні | RESET Clinic",
    metaDescription: "Випадіння волосся може мати багато причин. Пояснюємо роль дефіцитів, чому не існує універсального списку аналізів і з чого почати діагностику.",
    angle: "Cross-cluster nutrition + trichology, which sends to trichoscopy and deficiency diagnostics.",
    moneyPage: { label: "Лікування випадіння волосся", href: "/dermatology/hair-loss-treatment/" },
    supportingPages: [
      { label: "Трихоскопія", href: "/dermatology/trichoscopy/" },
      { label: "Діагностика дефіцитів", href: "/nutrition/deficiency-diagnostics/" },
    ],
  },
  {
    slug: "nutritsioloh-chy-diietoloh",
    title: "Нутриціолог чи дієтолог: у чому різниця і до кого звертатися",
    category: "nutrition",
    priority: "P2",
    intent: "comparison",
    primaryKeyword: "нутриціолог чи дієтолог",
    seoTitle: "Нутриціолог чи дієтолог: у чому різниця | RESET Clinic",
    metaDescription: "Розбираємо різницю між ролями спеціалістів, межі компетенцій та ситуації, коли потрібна саме медична консультація.",
    angle: "Comparison intent that supports local nutritionist landing without duplicating «нутриціолог Львів».",
    moneyPage: { label: "Нутриціолог у Львові", href: "/nutrition/nutritionist-lviv/" },
    supportingPages: [
      { label: "Нутриціологія", href: "/nutrition/" },
      { label: "Діагностика дефіцитів", href: "/nutrition/deficiency-diagnostics/" },
    ],
  },
  {
    slug: "analizy-na-defitsyty",
    title: "Аналізи на дефіцити: чому універсального чекліста не існує",
    category: "nutrition",
    priority: "P2",
    intent: "diagnostic",
    primaryKeyword: "аналізи на дефіцити",
    seoTitle: "Аналізи на дефіцити: що перевіряти і за чиїми показаннями | RESET Clinic",
    metaDescription: "Пояснюємо, чому набір лабораторних досліджень залежить від симптомів, анамнезу та раціону, а не від універсального «чекліста дефіцитів».",
    angle: "Myth-busting, conversion-friendly article for deficiency diagnostics.",
    moneyPage: { label: "Діагностика дефіцитів", href: "/nutrition/deficiency-diagnostics/" },
    supportingPages: [
      { label: "Вітамінно-мінеральні дефіцити", href: "/nutrition/vitamin-mineral-deficiencies/" },
      { label: "Консультація нутриціолога", href: "/nutrition/nutritionist-lviv/" },
    ],
  },
  {
    slug: "yak-pidhotuvatysia-do-nutritsioloha",
    title: "Як підготуватися до консультації нутриціолога",
    category: "nutrition",
    priority: "P3",
    intent: "pre-procedure",
    primaryKeyword: "як підготуватися до нутриціолога",
    seoTitle: "Як підготуватися до консультації нутриціолога | RESET Clinic",
    metaDescription: "Що варто підготувати перед консультацією нутриціолога: список препаратів і добавок, попередні аналізи, харчові звички та основні запити.",
    angle: "Bottom-funnel pre-consultation article that supports booking.",
    moneyPage: { label: "Нутриціолог у Львові", href: "/nutrition/nutritionist-lviv/" },
    supportingPages: [
      { label: "Нутриціологія", href: "/nutrition/" },
      { label: "Діагностика дефіцитів", href: "/nutrition/deficiency-diagnostics/" },
    ],
  },
];

export function getSeoContentPlanItem(slug?: string | null) {
  if (!slug) return null;
  return SEO_CONTENT_PLAN.find((item) => item.slug === slug) ?? null;
}

export function getSeoContentPlanByCategory(category: SeoContentPlanItem["category"]) {
  return SEO_CONTENT_PLAN.filter((item) => item.category === category);
}
