create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.admin_users (
  email text primary key,
  role text not null default 'admin' check (role in ('owner','admin','editor','analyst')),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users a
    where lower(a.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
      and a.enabled = true
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  status text not null default 'new' check (status in ('new','contacted','qualified','booked','won','lost','spam')),
  name text,
  phone text,
  email text,
  message text,
  service text,
  form_id text,
  page_url text,
  page_path text,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  gclid text,
  fbclid text,
  ttclid text,
  ip_hash text,
  user_agent text,
  payload jsonb not null default '{}'::jsonb,
  crm_status text not null default 'pending' check (crm_status in ('pending','sent','failed','disabled')),
  crm_external_id text,
  crm_error text
);

create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_status_idx on public.leads (status);
create index if not exists leads_utm_source_idx on public.leads (utm_source);

create table if not exists public.lead_events (
  id bigint generated by default as identity primary key,
  lead_id uuid not null references public.leads(id) on delete cascade,
  created_at timestamptz not null default now(),
  event_type text not null,
  note text,
  actor_email text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.blog_posts (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  slug text not null unique,
  title text not null,
  excerpt text,
  body text not null default '',
  author_name text,
  reviewer_name text,
  reviewer_title text,
  reviewed_at timestamptz,
  target_keyword text,
  seo_title text,
  seo_description text,
  canonical_url text,
  og_image text,
  faq jsonb not null default '[]'::jsonb,
  sources jsonb not null default '[]'::jsonb,
  schema_type text not null default 'MedicalWebPage',
  indexable boolean not null default true
);

create index if not exists blog_posts_status_idx on public.blog_posts (status, published_at desc);

create table if not exists public.seo_pages (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  path text not null unique,
  page_type text not null default 'page',
  status text not null default 'published' check (status in ('draft','published','archived')),
  primary_keyword text,
  cluster text,
  title text,
  description text,
  h1 text,
  canonical_url text,
  indexable boolean not null default true,
  schema_types text[] not null default '{}',
  word_count integer not null default 0,
  internal_links integer not null default 0,
  seo_score integer not null default 0 check (seo_score between 0 and 100),
  audit_issues jsonb not null default '[]'::jsonb,
  last_audited_at timestamptz,
  indexed_status text,
  last_crawled_at timestamptz
);

create index if not exists seo_pages_score_idx on public.seo_pages (seo_score desc);

create table if not exists public.search_console_daily (
  id bigint generated by default as identity primary key,
  date date not null,
  page text not null default '',
  query text not null default '',
  clicks numeric not null default 0,
  impressions numeric not null default 0,
  ctr numeric not null default 0,
  position numeric not null default 0,
  created_at timestamptz not null default now(),
  unique(date, page, query)
);

create index if not exists gsc_date_idx on public.search_console_daily (date desc);
create index if not exists gsc_page_idx on public.search_console_daily (page);

create table if not exists public.ga4_daily (
  id bigint generated by default as identity primary key,
  date date not null,
  landing_page text not null default '',
  source_medium text not null default '',
  sessions numeric not null default 0,
  users numeric not null default 0,
  conversions numeric not null default 0,
  created_at timestamptz not null default now(),
  unique(date, landing_page, source_medium)
);

create index if not exists ga4_date_idx on public.ga4_daily (date desc);

create table if not exists public.integration_sync_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  integration text not null,
  status text not null check (status in ('success','failed','skipped')),
  records_processed integer not null default 0,
  message text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.crm_integrations (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  provider text not null default 'webhook',
  name text not null default 'Primary CRM',
  enabled boolean not null default false,
  endpoint text,
  config jsonb not null default '{}'::jsonb,
  last_success_at timestamptz,
  last_error text
);

create trigger leads_set_updated_at before update on public.leads
for each row execute function public.set_updated_at();
create trigger blog_posts_set_updated_at before update on public.blog_posts
for each row execute function public.set_updated_at();
create trigger seo_pages_set_updated_at before update on public.seo_pages
for each row execute function public.set_updated_at();
create trigger admin_users_set_updated_at before update on public.admin_users
for each row execute function public.set_updated_at();
create trigger crm_integrations_set_updated_at before update on public.crm_integrations
for each row execute function public.set_updated_at();

alter table public.admin_users enable row level security;
alter table public.leads enable row level security;
alter table public.lead_events enable row level security;
alter table public.blog_posts enable row level security;
alter table public.seo_pages enable row level security;
alter table public.search_console_daily enable row level security;
alter table public.ga4_daily enable row level security;
alter table public.integration_sync_logs enable row level security;
alter table public.crm_integrations enable row level security;

create policy "admin_users_read_self" on public.admin_users
for select to authenticated
using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')) and enabled = true);

create policy "leads_public_insert" on public.leads
for insert to anon, authenticated
with check (true);
create policy "leads_admin_read" on public.leads
for select to authenticated using (public.is_admin());
create policy "leads_admin_update" on public.leads
for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "leads_admin_delete" on public.leads
for delete to authenticated using (public.is_admin());

create policy "lead_events_admin_all" on public.lead_events
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "blog_public_read_published" on public.blog_posts
for select to anon, authenticated
using (status = 'published' and indexable = true and published_at is not null and published_at <= now());
create policy "blog_admin_all" on public.blog_posts
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "seo_pages_admin_all" on public.seo_pages
for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "gsc_admin_all" on public.search_console_daily
for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "ga4_admin_all" on public.ga4_daily
for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "sync_logs_admin_all" on public.integration_sync_logs
for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "crm_integrations_admin_all" on public.crm_integrations
for all to authenticated using (public.is_admin()) with check (public.is_admin());

insert into public.seo_pages (path,page_type,status,title,description,canonical_url,indexable,schema_types,seo_score)
values
('/', 'homepage', 'published', 'RESET Clinic Львів — клініка естетичної медицини', 'RESET Clinic у Львові: дерматологія, косметологія, трихологія, нутриціологія та сімейна медицина.', 'https://resetclinic.org/', true, array['MedicalClinic','WebSite','WebPage'], 92),
('/services/', 'hub', 'published', 'Косметологія та дерматологія у Львові — RESET Clinic', 'Послуги RESET Clinic у Львові.', 'https://resetclinic.org/services/', true, array['CollectionPage','ItemList','Service','BreadcrumbList'], 92),
('/doctors/', 'doctor_hub', 'published', 'Лікарі-косметологи та дерматологи у Львові | RESET Clinic', 'Команда лікарів RESET Clinic у Львові.', 'https://resetclinic.org/doctors/', true, array['CollectionPage','BreadcrumbList'], 88),
('/price/', 'price', 'published', 'Ціни на косметологію у Львові — прайс | RESET Clinic', 'Актуальні ціни RESET Clinic у Львові.', 'https://resetclinic.org/price/', true, array['CollectionPage','BreadcrumbList'], 90),
('/about/', 'about', 'published', 'Про RESET Clinic — клініка естетичної медицини у Львові', 'Про RESET Clinic у Львові.', 'https://resetclinic.org/about/', true, array['AboutPage','BreadcrumbList'], 90),
('/contacts/', 'contact', 'published', 'Контакти RESET Clinic у Львові — Кульпарківська, 93/2', 'RESET Clinic: м. Львів, вул. Кульпарківська, 93/2.', 'https://resetclinic.org/contacts/', true, array['ContactPage','BreadcrumbList'], 92),
('/booking/', 'utility', 'published', 'Записатися на прийом | RESET Clinic', 'Онлайн-запис на консультацію або процедуру.', 'https://resetclinic.org/booking/', false, array['WebPage'], 80),
('/thank-you/', 'utility', 'published', 'Дякуємо за заявку | RESET Clinic', 'Заявку успішно отримано.', 'https://resetclinic.org/thank-you/', false, array['WebPage'], 80)
on conflict (path) do nothing;
